export enum QueryKey {
    AUTH_LOGIN = "auth/login",
    AUTH_REFRESH = "auth/refresh",
    AUTH_LOGOUT = "auth/logout",
    ME = "accounts/me",
    USERS = "users",
    TEACHERS = "teachers",
    STAFFS = "staffs",
    ACADEMIC_YEARS = "academic-years",
    CLASSES = "class-rooms",
    IMAGES = "upload/images",
    SUBJECTS = 'subjects',
    CLASSROUTINE = 'class-routines',
    ROOM_TYPES = "dormitory-system/room-types",
    DORMITORY = "dormitory-system/dormitories",
    DORMITORY_ROOMS = "dormitory-system/dormitory-rooms",
};
