export enum QueryKey {
    AUTH_LOGIN = "auth/login",
    AUTH_REFRESH = "auth/refresh",
    AUTH_LOGOUT = "auth/logout",
    ME = "accounts/me",
    USERS = "users",
    TEACHERS = "teachers",
    STAFFS = "staffs",
    STUDENTS = "students",
    ACADEMIC_YEARS = "academic-years",
    CLASSES = "class-rooms",
    SECTIONS = "sections",
    IMAGES = "upload/images",
    SUBJECTS = 'subjects',
    CLASSROUTINE = 'class-routines',
    ROOM_TYPES = "dormitory-system/room-types",
    DORMITORY = "dormitory-system/dormitories",
    DORMITORY_ROOMS = "dormitory-system/dormitory-rooms",
    ENROLLMENTS = "enrollments",
    OPTIONS = "options",
    ATTENDANCES = "attendances",
    LEAVE_REQUESTS = "leave-requests",
    EMPLOYEES = "employees",
    LIBRARY_BOOKS = "library-books",
    BOOK_TRANSACTIONS = "book-transactions",
    BOOK_CATEGORIES = "book-categories",
};
